// This file was auto-generated by prisma-generator-typescript-interfaces

export type ScrumPointUnit = "MINUTE" | "HOUR" | "DAY" | "MONTH";

export type Role = "SCRUM_MASTER" | "USER";

export type NotificationType = "GameStarted" | "Invitation";

export type OrgRole = "OWNER" | "ADMIN" | "MEMBER";

export interface Account {
  id: string;
  userId: string;
  type: string;
  provider: string;
  providerAccountId: string;
  refresh_token: string | null;
  access_token: string | null;
  expires_at: number | null;
  token_type: string | null;
  scope: string | null;
  id_token: string | null;
  session_state: string | null;
  refresh_token_expires_in: number | null;
  user?: User;
}

export interface Session {
  id: string;
  sessionToken: string;
  userId: string;
  expires: Date;
  user?: User;
}

export interface Organization {
  id: string;
  name: string;
  atlassianCloudId: string;
  baseUrl: string | null;
  avatarUrl: string | null;
  createdAt: Date;
  updatedAt: Date;
  users?: UserOrganization[];
  rooms?: Room[];
  User?: User[];
  gameSettings?: GameSettings | null;
  pointPresets?: ScrumPointPreset[];
}

export interface GameSettings {
  id: string;
  autoShowResults: boolean;
  autoShowResultsTime: Decimal;
  onlyScrumMasterCanShowResults: boolean;
  lockVotes: boolean;
  notifyOnVote: boolean;
  notifyOnJoin: boolean;
  persistentLeave: boolean;
  scrumPoints?: ScrumPoint[];
  activePresetId: string | null;
  activePreset?: ScrumPointPreset | null;
  organizationId: string;
  organization?: Organization;
}

export interface ScrumPoint {
  id: string;
  value: number;
  timeStart: number;
  timeEnd: number;
  valueStartUnit: ScrumPointUnit;
  valueEndUnit: ScrumPointUnit;
  position: number;
  gameSettingsId: string;
  gameSettings?: GameSettings;
  votes?: Vote[];
}

export interface ScrumPointPreset {
  id: string;
  organizationId: string;
  name: string;
  description: string | null;
  isDefault: boolean;
  createdByUserId: string | null;
  createdAt: Date;
  updatedAt: Date;
  organization?: Organization;
  createdBy?: User | null;
  items?: ScrumPointPresetItem[];
  settingsUsing?: GameSettings[];
}

export interface ScrumPointPresetItem {
  id: string;
  presetId: string;
  value: number;
  timeStart: number;
  timeEnd: number;
  valueStartUnit: ScrumPointUnit;
  valueEndUnit: ScrumPointUnit;
  position: number;
  preset?: ScrumPointPreset;
}

export interface UserOrganization {
  organizationId: string;
  userId: string;
  role: OrgRole;
  joinedAt: Date;
  organization?: Organization;
  user?: User;
}

export interface User {
  id: string;
  name: string | null;
  email: string | null;
  emailVerified: Date | null;
  image: string | null;
  accounts?: Account[];
  Game?: Game[];
  invitations?: Invitation[];
  notifications?: Notification[];
  rooms?: RoomUser[];
  sessions?: Session[];
  votes?: Vote[];
  ScrumPointPreset?: ScrumPointPreset[];
  organizations?: UserOrganization[];
  activeOrganizationId: string | null;
  activeOrganization?: Organization | null;
}

export interface VerificationToken {
  identifier: string;
  token: string;
  expires: Date;
}

export interface Room {
  id: string;
  name: string;
  createdAt: Date;
  games?: Game[];
  invitations?: Invitation[];
  users?: RoomUser[];
  organizationId: string;
  organization?: Organization;
}

export interface RoomUser {
  userId: string;
  roomId: string;
  role: Role;
  joinedAt: Date;
  room?: Room;
  user?: User;
}

export interface Invitation {
  id: string;
  roomId: string;
  email: string;
  token: string;
  invitedById: string;
  accepted: boolean;
  createdAt: Date;
  acceptedAt: Date | null;
  invitedBy?: User;
  room?: Room;
}

export interface Notification {
  id: string;
  userId: string;
  type: NotificationType;
  message: string;
  data: JsonValue | null;
  read: boolean;
  createdAt: Date;
  user?: User;
}

export interface Game {
  id: string;
  roomId: string;
  scrumMasterId: string;
  createdAt: Date;
  endedAt: Date | null;
  room?: Room;
  scrumMaster?: User;
  votes?: Vote[];
}

export interface Vote {
  id: number;
  gameId: string;
  userId: string;
  scrumPointId: string | null;
  scrumPoint?: ScrumPoint | null;
  game?: Game;
  user?: User;
}

type Decimal = { valueOf(): string };

type JsonValue = string | number | boolean | { [key in string]?: JsonValue } | Array<JsonValue> | null;
