import "@/styles/globals.css";

import { type Metadata } from "next";
import { Geist } from "next/font/google";

import { TRPCReactProvider } from "@/trpc/react";
import ProtectedSidebar from "@/app/_components/protected-sidebar";
import { auth } from "@/server/auth";
import { ThemeProvider } from "next-themes";
import { Toaster } from "@/components/ui/sonner";
import { SessionProvider } from "next-auth/react";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default async function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  const session = await auth();

  return (
    <html lang="en" className={`${geist.variable}`} suppressHydrationWarning>
      <body className="min-h-screen bg-background antialiased overflow-hidden">
        <ThemeProvider attribute='class' defaultTheme="dark" enableSystem disableTransitionOnChange>
          <SessionProvider session={session}>
            <TRPCReactProvider>
          {children}

          <ProtectedSidebar isAuthorized={Boolean(session)} />
          <Toaster closeButton position="bottom-right" expand />
        </TRPCReactProvider>
          </SessionProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
